---
title: "Wireless Review"
date: "2014-03-29"
categories:
    - "hugo"
    - "fun"
    - "test"
---

= Wireless Review
:stem: latexmath
:experimental:
:diagram:
:source-highlighter: prettify

# Quiz


++++
<div id="chapter7">
<h1 class="quizName"><!-- where the quiz name goes --></h1>

<div class="quizArea">
<div class="quizHeader">

<a class="startQuiz" href="#">Get Started!</a>
</div>

<!-- where the quiz gets built -->
</div>

<div class="quizResults">
<h3 class="quizScore">You Scored: <span><!-- where the quiz score goes --></span></h3>

<h3 class="quizLevel"><strong>Ranking:</strong> <span><!-- where the quiz ranking level goes --></span></h3>

<div class="quizResultsCopy">
</div>
</div>
</div>

<div id="chapter8">
<h1 class="quizName"><!-- where the quiz name goes --></h1>

<div class="quizArea">
<div class="quizHeader">

<a class="startQuiz" href="#">Get Started!</a>
</div>

<!-- where the quiz gets built -->
</div>

<div class="quizResults">
<h3 class="quizScore">You Scored: <span><!-- where the quiz score goes --></span></h3>

<h3 class="quizLevel"><strong>Ranking:</strong> <span><!-- where the quiz ranking level goes --></span></h3>

<div class="quizResultsCopy">
</div>
</div>
</div>

<div id="chapter9">
<h1 class="quizName"><!-- where the quiz name goes --></h1>

<div class="quizArea">
<div class="quizHeader">

<a class="startQuiz" href="#">Get Started!</a>
</div>

<!-- where the quiz gets built -->
</div>

<div class="quizResults">
<h3 class="quizScore">You Scored: <span><!-- where the quiz score goes --></span></h3>

<h3 class="quizLevel"><strong>Ranking:</strong> <span><!-- where the quiz ranking level goes --></span></h3>

<div class="quizResultsCopy">
</div>
</div>
</div>


<script>
var chapter7 = {
    "info": {
        "name":    "",
        "main":    "Chapter 7 Quiz",
    },
    "questions": [
        { 
            "q": "An 802.11 wireless network name is known as which type of address? (Choose all that apply.)",
            "a": [
                {"option": "BSSID",      "correct": false},
                {"option": "MAC Address",     "correct": false},
                {"option": "IP Address",      "correct": false},
                {"option": "SSID",     "correct": true},
                {"option": "Extended service set identifier", "correct": true}
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, The service set identifier (SSID) is a 32-character, case-sensitive, logical name used to identify a wireless network. An extended service set identifier (ESSID) is the logical network name used in an extended service set. ESSID is often synonymous with SSID."
        },
        { 
            "q": "Which two 802.11 topologies require the use of an access point?",
            "a": [
                {"option": "WPAN",      "correct": false},
                {"option": "IBSS",     "correct": false},
                {"option": "Basic service set",     "correct": true},
                {"option": "Ad hoc",      "correct": false},
                {"option": "ESS",     "correct": true}
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, The 802.11 standard defines four service sets, or topologies. A basic service set (BSS) is defined as one AP and associated clients. An extended service set (ESS) is defined as one or more basic service sets connected by a distribution system medium. An independent basic service set (IBSS) does not use an AP and consists solely of client stations (STAs)."
        },
        { 
            "q": "The 802.11 standard defines which medium to be used in a distribution system (DS)?",
            "a": [
                {"option": "802.3 Ethernet",      "correct": false},
                {"option": "802.15",     "correct": false},
                {"option": "802.5 token ring",      "correct": false},
                {"option": "Star-bus topology",     "correct": false},
                {"option": "None of the above",     "correct": true}
            ],
            "correct": "Correct",
            "incorrect": "Wrong, By design, the 802.11 standard does not specify a medium to be used in the distribution system. The distribution system medium (DSM) may be an 802.3 Ethernet backbone, an 802.5 token ring network, a wireless medium, or any other medium."
        },

    { "q":"Which option is a wireless computer topology used for communication of computer devices within close proximity of a person?",
    "a": [
    {"option":"WWAN", "correct": false},
    {"option":"Bluetooth", "correct": false},
    {"option":"ZigBee", "correct": false},
    {"option":"WPAN", "correct": true},
    {"option":"WMAN", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, A wireless personal area network (WPAN) is a short-distance wireless topology. Bluetooth and ZigBee are technologies that are often used in WPANs."
    },
    { "q":"Which 802.11 service set may allow for client roaming?",
    "a": [
    {"option":"ESS", "correct": true},
    {"option":"Basic service set", "correct": false},
    {"option":"IBSS", "correct": false},
    {"option":"Spread spectrum service set", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, The most common implementation of an extended service set (ESS) has access points with partially overlapping coverage cells. The purpose behind an ESS with partially overlapping coverage cells is seamless roaming."
    },
    { "q":"What factors might affect the size of a BSA coverage area of an access point? (Choose all that apply.)",
    "a": [
    {"option":"Antenna gain", "correct": true},
    {"option":"CSMA/CA", "correct": false},
    {"option":"Transmission power", "correct": true},
    {"option":"Indoor/outdoor surroundings", "correct": true},
    {"option":"Distribution system", "correct": false}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong,  The size and shape of a basic service area can depend on many variables, including AP transmit power, antenna gain, and physical surroundings."
    },
    { "q":"What is the default configuration mode that allows an AP radio to operate in a basic service set?",
    "a": [
    {"option":"Scanner", "correct": false},
    {"option":"Repeater", "correct": false},
    {"option":"Root", "correct": true},
    {"option":"Access", "correct": false},
    {"option":"Nonroot", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong,  The normal default setting of an access point is root mode, which allows the AP to transfer data back and forth between the DS and the 802.11 wireless medium. The default root configuration of an AP allows it to operate inside a basic service set (BSS)."
    },
    { "q":"Which terms describe an 802.11 topology involving STAs but no access points? (Choose all that apply.)",
    "a": [
    {"option":"BSS", "correct": false},
    {"option":"Ad hoc", "correct": true},
    {"option":"DSSS", "correct": false},
    {"option":"Infrastructure", "correct": false},
    {"option":"IBSS", "correct": true},
    {"option":"Peer-to-peer", "correct": true}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong, The 802.11 standard defines an independent basic service set (IBSS) as a service set using client peer-to-peer communications without the use of an AP. Other names for an IBSS include ad hoc and peer-to-peer. "
    },
    { "q":"STAs operating in Infrastructure mode may communicate in which of the following scenarios? (Choose all that apply.)",
    "a": [
    {"option":"802.11 frame exchanges with other STAs via an AP", "correct": true},
    {"option":"802.11 frame exchanges with an AP in scanner mode", "correct": false},
    {"option":"802.11 frame peer-to-peer exchanges directly with other STAs", "correct": false},
    {"option":"Frame exchanges with network devices on the DSM", "correct": true},
    {"option":"All of the above", "correct": false}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong,Clients that are configured in Infrastructure mode may communicate via the AP with other wireless client stations within a BSS. Clients may also communicate through the AP with other networking devices that exist on the distribution system medium, such as a server or a wired desktop. "
    },
    { "q":"Which of these are included in the four topologies defined by the 802.11-2012 standard? (Choose all that apply.)",
    "a": [
    {"option":"DSSS", "correct": false},
    {"option":"ESS", "correct": true},
    {"option":"BSS", "correct": true},
    {"option":"IBSS", "correct": true},
    {"option":"FHSS", "correct": false}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong, The four topologies, or service sets, defined by the 802.11-2012 standard are basic service set (BSS), extended service set (ESS), independent basic service set (IBSS), and mesh basic service set (MBSS). DSSS and FHSS are spread spectrum technologies."
    },
    { "q":"Which wireless topology provides citywide wireless coverage?",
    "a": [
    {"option":"WMAN", "correct": true},
    {"option":"WLAN", "correct": false},
    {"option":"WPAN", "correct": false},
    {"option":"WAN", "correct": false},
    {"option":"WWAN", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, A wireless metropolitan area network (WMAN) provides coverage to a metropolitan area such as a city and the surrounding suburbs."
    },
    { "q":"At which layer of the OSI model will a BSSID address be used?",
    "a": [
    {"option":"Physical", "correct": false},
    {"option":"Network", "correct": false},
    {"option":"Session", "correct": false},
    {"option":"Data-Link", "correct": true},
    {"option":"Application", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, The basic service set identifier (BSSID) is a 48-bit (6-octet) MAC address. MAC addresses exist at the MAC sublayer of the Data-Link layer of the OSI model."
    },
    { "q":"The basic service set identifier address can be found in which topologies? (Choose all that apply.)",
    "a": [
    {"option":"FHSS", "correct": false},
    {"option":"IBSS", "correct": true},
    {"option":"ESS", "correct": true},
    {"option":"HR-DSSS", "correct": false},
    {"option":"BSS", "correct": true}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong, The BSSID is the layer 2 identifier of either a BSS or an IBSS service set. The 48-bit (6-octet) MAC address of an access point's radio is the basic service set identifier (BSSID) within a BSS. An ESS topology utilizes multiple access points, thus the existence of multiple BSSIDs. In an IBSS network, the first station that powers up randomly generates a virtual BSSID in the MAC address format. FHSS and HR-DSSS are spread spectrum technologies."
    },
    { "q":"Which 802.11 service set defines mechanisms for mesh networking?",
    "a": [
    {"option":"BSS", "correct": false},
    {"option":"DSSS", "correct": false},
    {"option":"ESS", "correct": false},
    {"option":"MBSS", "correct": true},
    {"option":"IBSS", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, The 802.11s-2011 amendment, which is now part of the 802.11-2012 standard, defined a new service set for an 802.11 mesh topology. When access points support mesh functions, they may be deployed where wired network access is not possible. The mesh functions are used to provide wireless distribution of network traffic, and the set of APs that provide mesh distribution form a mesh basic service set (MBSS)."
    },
    { "q":"What method of dialog communications is used within an 802.11 WLAN?",
    "a": [
    {"option":"Simplex communications", "correct": false},
    {"option":"Half-duplex communications", "correct": true},
    {"option":"Full-duplex communications", "correct": false},
    {"option":"Dual-duplex communications", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, In half-duplex communications, both devices are capable of transmitting and receiving; however, only one device can transmit at a time. Walkie-talkies, or two-way radios, are examples of half-duplex devices. IEEE 802.11 wireless networks use half-duplex communications."
    },
    { "q":"What are some operational modes in which an AP radio may be configured? (Choose all that apply.)",
    "a": [
    {"option":"Scanner", "correct": true},
    {"option":"Root", "correct": true},
    {"option":"Bridge", "correct": true},
    {"option":"Mesh", "correct": true},
    {"option":"Repeater", "correct": true}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong,  The default standard mode for an access point is root mode. Other operational modes include bridge, workgroup bridge, mesh, scanner, and repeater modes."
    },
    { "q":"A network consisting of clients and two or more access points with the same SSID connected by an 802.3 Ethernet backbone is one example of which 802.11 topology? (Choose all that apply.)",
    "a": [
    {"option":"ESS", "correct": true},
    {"option":"Basic service set", "correct": false},
    {"option":"Extended service set", "correct": true},
    {"option":"IBSS", "correct": false},
    {"option":"Ethernet service set", "correct": false}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong, An extended service set (ESS) is two or more basic service sets connected by a distribution system. An ESS is a collection of multiple access points and their associated client stations, all united by a single distribution system medium."
    },
    { "q":"What term best describes two access points communicating with each other wirelessly while also allowing clients to communicate through the access points?",
    "a": [
    {"option":"WDS", "correct": true},
    {"option":"DS", "correct": false},
    {"option":"DSS", "correct": false},
    {"option":"DSSS", "correct": false},
    {"option":"DSM", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong, A wireless distribution system (WDS) can connect access points together using a wireless backhaul while allowing clients to also associate to the radios in the access points."
    },
    { "q":"What components make up a distribution system? (Choose all that apply.)",
    "a": [
    {"option":"HR-DSSS", "correct": false},
    {"option":"Distribution system services", "correct": true},
    {"option":"DSM", "correct": true},
    {"option":"DSSS", "correct": false},
    {"option":"Intrusion detection system", "correct": false}
    ],
    "select_any": false,
    "correct": "Correct",
    "incorrect": "Wrong, The distribution system consists of two main components. The distribution system medium (DSM) is a logical physical medium used to connect access points. Distribution system services (DSS) consist of services built inside an access point, usually in the form of software."
    },
    { "q":"What type of wireless topology is defined by the 802.11 standard?",
    "a": [
    {"option":"WAN", "correct": false},
    {"option":"WLAN", "correct": true},
    {"option":"WWAN", "correct": false},
    {"option":"WMAN", "correct": false},
    {"option":"WPAN", "correct": false}
    ],
    "correct": "Correct",
    "incorrect": "Wrong,  The 802.11 standard is considered a wireless local area network (WLAN) standard. 802.11 hardware can, however, be utilized in other wireless topologies."
    } ]
    };


var chapter8 = {
    "info": {
        "name":    "",
        "main":    "Chapter 8 Quiz",
    },
    "questions": []
    }


var chapter9 = {
    "info": {
        "name":    "",
        "main":    "Chapter 9 Quiz",
    },
    "questions": [
        {
            "q": "What is the difference between association frames and reassociation frames?",
            "a": [
            {"option": "Association frames are management frames, whereas reassociation frames are control frames.", "correct": false },
            {"option": "Association frames are used exclusively for roaming.", "correct": false },
            {"option": "Reassociation frames contain the BSSID of the original AP.", "correct": false },
            {"option": "Only association frames are used to join a BSS.", "correct": true },
            ],
            "correct": "Correct",
            "incorrect": "Wrong, Both frames are used to join a BSS. Reassociation frames are used during the roaming process. The reassociation frame contains an additional field called Current AP Address. This address is the BSSID of the original AP that the client is leaving."
            },
            {
            "q": "Which of the following contains only LLC data and the IP packet but does not include any 802.11 data?",
            "a": [
            {"option": "MPDU", "correct": false },
            {"option": "PPDU", "correct": false },
            {"option": "PSDU", "correct": false },
            {"option": "MSDU", "correct": true },
            {"option": "MMPDU", "correct": false },
            ],
            "correct": "Correct",
            "incorrect": "Wrong, An IP packet consists of layer 3–7 information. The MAC Service Data Unit (MSDU) contains data from the LLC sublayer and/or any number of layers above the Data-Link layer. The MSDU is the payload found inside the body of 802.11 data frames."
            },

            {
            "q": "Which of the following are protection mechanisms? (Choose all that apply.)",
            "a": [
            { "option": "NAV back-off", "correct": false },
            { "option": "RTS/CTS", "correct": true },
            { "option": "RTS-to-Self", "correct": false },
            { "option": "CTS-to-Self", "correct": true },
            { "option": "WEP encryption", "correct": false }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, RTS/CTS and CTS-to-Self provide 802.11g protection mechanisms, sometimes referred to as mixed-mode support. NAV back-off and RTS-to-Self do not exist. WEP encryption provides data security."
            },
            {
            "q": "The presence of what type of transmissions can trigger the protection mechanism within an ERP basic service set? (Choose all that apply.)",
            "a": [
            { "option": "Association of an HR-DSSS client", "correct": true },
            { "option": "Association of an ERP-OFDM client", "correct": false },
            { "option": "HR-DSSS beacon frame", "correct": true },
            { "option": "ERP beacon frame with the NonERP_Present bit set to 1", "correct": true },
            { "option": "Association of an FHSS client", "correct": false }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, An ERP AP signals for the use of the protection mechanism in the ERP information element in the beacon frame. If a non-ERP STA associates to an ERP AP, the ERP AP will enable the NonERP_Present bit in its own beacons, enabling protection mechanisms in its BSS. In other words, an HR-DSSS (802.11b) client association will trigger protection. If an ERP AP hears a beacon with only an 802.11b or 802.11 supported rate set from another AP or an IBSS STA, it will enable the NonERP_Present bit in its own beacons, enabling protection mechanisms in its BSS."
            },
            {
            "q": "Which of the following information is included in a probe response frame? (Choose all that apply.)",
            "a": [
            { "option": "Time stamp", "correct": true },
            { "option": "Supported data rates", "correct": true },
            { "option": "Service set capabilities", "correct": true },
            { "option": "SSID", "correct": true },
            { "option": "Traffic indication map", "correct": false }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, The probe response contains the same information as the beacon frame, with the exception of the traffic indication map."
            },
            {
            "q": "Which of the following are true about beacon management frames? (Choose all that apply.)",
            "a": [
            { "option": "Beacons can be disabled to hide the network from intruders.", "correct": false },
            { "option": "Time-stamp information is used by the clients to synchronize their clocks.", "correct": true },
            { "option": "In a BSS, clients share the responsibility of transmitting the beacons.", "correct": false },
            { "option": "Beacons can contain vendor-proprietary information.", "correct": true }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, Beacons cannot be disabled. Clients use the time-stamp information from the beacon to synchronize with the other stations on the wireless network. Only APs send beacons in a BSS; client stations send beacons in an IBSS. Beacons can contain proprietary information."
            },

            {
            "q": "If WMM-PS is not supported, after a station sees its AID set to 1 in the TIM, what typically is the next frame that the station transmits?",
            "a": [
            { "option": "CTS", "correct": false },
            { "option": "PS-Poll", "correct": true },
            { "option": "ATIM", "correct": false },
            { "option": "ACK", "correct": false }
            ],
            "correct": "Correct",
            "incorrect": "Wrong, . If a station finds its AID in the TIM, there is unicast data on the AP that the station needs to stay awake for and request to have downloaded. This request is performed by a PS-Poll frame."
            },

            {
            "q": "When a station sends an RTS, the Duration/ID field notifies the other stations that they must set their NAV timers to which of the following values?",
            "a": [
            { "option": "213 microseconds", "correct": false },
            { "option": "The time necessary to transmit the DATA and ACK frames", "correct": false },
            { "option": "The time necessary to transmit the CTS frame", "correct": false },
            { "option": "The time necessary to transmit the CTS, DATA, and ACK frames", "correct": true }
            ],
            "correct": "Correct",
            "incorrect": "Wrong, When the RTS frame is sent, the value of the Duration/ID field is equal to the time necessary for the CTS, DATA, and ACK frames to be transmitted."
            },

            {
            "q": "How does a client station indicate that it is using Power Save mode?",
            "a": [
            { "option": "It transmits a frame to the AP with the Sleep field set to 1.", "correct": false },
            { "option": "It transmits a frame to the AP with the Power Management field set to 1.", "correct": true },
            { "option": "Using DTIM, the AP determines when the client station uses Power Save mode.", "correct": false },
            { "option": "It doesn't need to, because Power Save mode is the default.", "correct": false }
            ],
            "correct": "Correct",
            "incorrect": "Wrong,  When the client station transmits a frame with the Power Management field set to 1, it is enabling Power Save mode. The DTIM does not enable Power Save mode; it only notifies clients to stay awake in preparation for a multicast or broadcast."
            },
            {
            "q": "What would cause an 802.11 station to retransmit a unicast frame? (Choose all that apply.)",
            "a": [
            { "option": "The transmitted unicast frame was corrupted.", "correct": true },
            { "option": "The ACK frame from the receiver was corrupted.", "correct": true },
            { "option": "The receiver's buffer was full.", "correct": false },
            { "option": "The transmitting station will never attempt to retransmit the data frame.", "correct": false },
            { "option": "The transmitting station will send a retransmit notification.", "correct": false }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, The receiving station may have received the data, but the returning ACK frame may have become corrupted and the original unicast frame will have to be retransmitted. If the unicast frame becomes corrupted for any reason, the receiving station will not send an ACK."
            },

            {
            "q": "If a station is in Power Save mode, how does it know that the AP has buffered unicast frames waiting for it?",
            "a": [
            { "option": "By examining the PS-Poll frame", "correct": false },
            { "option": "By examining the TIM field", "correct": true },
            { "option": "When it receives an ATIM", "correct": false },
            { "option": "When the Power Management bit is set to 1", "correct": false },
            { "option": "From the DTIM interval", "correct": false }
            ],
            "correct": "Correct",
            "incorrect": "Wrong, The PS-Poll frame is used by the station to request cached data. The ATIM is used to notify stations in an IBSS of cached data. The Power Management bit is used by the station to notify the AP that the station is going into Power Save mode. The DTIM is used to indicate to client stations how often to wake up to receive buffered broadcast and multicast frames. The traffic indication map (TIM) is a field in the beacon frame used by the AP to indicate that there are buffered unicast frames for clients in Power Save mode."
            },

            {
            "q": "When is an ERP (802.11g) AP required by the IEEE 802.11-2012 standard to respond to probe request frames from nearby HR-DSSS (802.11b) stations? (Choose all that apply.)",
            "a": [
            { "option": "When the probe request frames contain a null SSID value", "correct": true },
            { "option": "When the AP supports only ERP-OFDM data rates", "correct": false },
            { "option": "When the AP supports only HR/DSSS data rates", "correct": false },
            { "option": "When the Power Management bit is set to 1", "correct": false },
            { "option": "When the probe request frames contain the correct SSID value", "correct": true }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong,  All 802.11 APs are required to respond to directed probe request frames that contain the correct SSID value. The AP must also respond to null probe request frames that contain a blank SSID value. Some vendors offer the capability to respond to null probe requests with a null probe response."
            },

            {
            "q": "Which of the following are true about scanning? (Choose all that apply.)",
            "a": [
            { "option": "There are two types of scanning: passive and active.", "correct": true },
            { "option": "Stations must transmit probe requests in order to learn about local APs.", "correct": false },
            { "option": "The 802.11 standard allows APs to ignore probe requests for security reasons.", "correct": false },
            { "option": "It is common for stations to continue to send probe requests after being associated to an AP.", "correct": true }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, There are two types of scanning: passive, which occurs when a station listens to the beacons to discover an AP, and active, which occurs when a station sends probe requests looking for APs. Stations send probe requests only if they are performing an active scan. After a station is associated, it is common for the station to continue to learn about nearby APs. All client stations maintain a “known AP” list that is constantly updated by active scanning."
            },

            {
            "q": "Given that an 802.11 MAC header can have as many as four MAC addresses, which type of addresses are not found in an 802.3 MAC header? (Choose all that apply.)",
            "a": [
            { "option": "SA", "correct": false },
            { "option": "BSSID", "correct": true },
            { "option": "DA", "correct": false },
            { "option": "RA", "correct": true },
            { "option": "TA", "correct": true }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong,  Although there are similarities, the addressing used by 802.11 MAC frames is much more complex than Ethernet frames. 802.3 frames have only a source address (SA) and destination address (DA) in the layer 2 header. The four MAC addresses used by an 802.11 frame can be used as five different types of addresses: receiver address (RA), transmitter address (TA), basic service set identifier (BSSID), destination address (DA), and source address (SA)."
            },

            {
            "q": "When a client station is first powered on, what is the order of frames generated by the client station and AP?",
            "a": [
            { "option": "Probe request/probe response, association request/response, authentication request/response", "correct": false },
            { "option": "Probe request/probe response, authentication request/response, association request/response", "correct": true },
            { "option": "Association request/response, authentication request/response, probe request/probe response", "correct": false },
            { "option": "Authentication request/response, association request/response, probe request/probe response", "correct": false }
            ],
            "correct": "Correct",
            "incorrect": "Wrong, When the client first attempts to connect to an AP, it will first send a probe request and listen for a probe response. After it receives a probe response, it will attempt to authenticate to the AP and then associate to the network."
            },

            {
            "q": "WLAN users have recently complained about gaps in audio and problems with the push-to-talk capabilities with the ACME Company's VoWiFi phones. What could be the cause of this problem?",
            "a": [
            { "option": "Misconfigured TIM setting", "correct": false },
            { "option": "Misconfigured DTIM setting", "correct": true },
            { "option": "Misconfigured ATIM setting", "correct": false },
            { "option": "Misconfigured BTIM setting", "correct": false }
            ],
            "correct": "Correct",
            "incorrect": "Wrong, The delivery traffic indication message (DTIM) is used to ensure that all stations using power management are awake when multicast or broadcast traffic is sent. The DTIM interval is important for any application that uses multicasting. For example, many VoWiFi vendors support push-to-talk capabilities that send VoIP traffic to a multicast address. A misconfigured DTIM interval would cause performance issues during a push-to-talk multicast."
            },

            {
            "q": "The WLAN help desk gets a call that all of the sudden, all of the HR-DSSS (802.11b) VoWiFi phones cannot connect to any of the ERP (802.11g) lightweight APs that are managed by a multiple-channel architecture WLAN controller. All the laptops with ERP (802.11g) radios can still connect. What are the possible causes of this problem? (Choose all that apply.)",
            "a": [
            { "option": "The WLAN admin disabled the 1, 2, 5.5, and 11 Mbps data rates on the controller.", "correct": true },
            { "option": "The WLAN admin disabled the 6 and 9 Mbps data rates on the controller.", "correct": false },
            { "option": "The WLAN admin enabled the 6 and 9 Mbps data rates on the controller as basic rates.", "correct": true },
            { "option": "The WLAN admin configured all the APs on channel 6.", "correct": false }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, An ERP (802.11g) AP is backward compatible with HR-DSSS and supports the data rates of 1, 2, 5.5, and 11 Mbps as well as the ERP-OFDM data rates of 6, 9, 12, 18, 24, 36, 48, and 54 Mbps. If a WLAN admin disabled the 1, 2, 5.5, and 11 Mbps data rates, backward compatibility will effectively be disabled and the HR-DSSS clients will not be able to connect. The 802.11-2012 standard defines the use of basic rates, which are required rates. If a client station does not support any of the basic rates used by an AP, the client station will be denied association to the BSS. If a WLAN admin configured the ERP-OFDM data rates of 6 and 9 Mbps as basic rates, the HR-DSSS clients would be denied association because they do not support those rates."
            },

            {
            "q": "In a multiple-channel architecture, roaming is controlled by the client station and occurs based on a set of proprietary rules determined by the manufacturer of the wireless radio. Which of the following parameters are often used when making the decision to roam? (Choose all that apply.)",
            "a": [
            { "option": "Received signal level", "correct": true },
            { "option": "Distance", "correct": false },
            { "option": "SNR", "correct": true },
            { "option": "WMM access categories", "correct": false }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong,  The amplitude of the received signals from the APs is usually the main variable when clients make a roaming decision. Client roaming mechanisms are often based on RSSI values, including received signal levels and signal-to-noise ratio (SNR). Distance and WMM access categories have nothing to do with the client's decision to roam to a new AP."
            },
            {
            "q": "What are some of the advantages of using U-APSD and WMM-PS power management over legacy power-management methods? (Choose all that apply.)",
            "a": [
            { "option": "Applications control doze time and trigger frames.", "correct": true },
            { "option": "U-APSD APs transmit all voice and video data immediately.", "correct": false },
            { "option": "The client does not have to wait for a beacon to request data.", "correct": true },
            { "option": "Downlink traffic is sent in a frame burst.", "correct": true },
            { "option": "Data frames are used as trigger frames. PS-Poll frames are not used.", "correct": true }
            ],
            "select_any": false,
            "correct": "Correct",
            "incorrect": "Wrong, Applications now control the power-save management behavior by setting doze periods and sending trigger frames. Clients using time-sensitive applications will send triggers to the AP frequently, while clients using more latency-tolerant applications will have a longer doze period. The trigger and delivery method eliminates the need for PS-Poll frames. The client can request to download buffered traffic and does not have to wait for a beacon frame. All the downlink application traffic is sent in a faster frame burst during the AP's TXOP."
            },

            {
            "q": "WMM-PS is based on which 802.11-2012 power-management method?",
            "a": [
            { "option": "S-APSD", "correct": false },
            { "option": "U-APSD", "correct": true },
            { "option": "PSMP", "correct": false },
            { "option": "SM Power Save", "correct": false },
            { "option": "PS-Poll", "correct": false }
            ],
            "correct": "Correct",
            "incorrect": "Wrong, The IEEE 802.11-2007 standard defines an enhanced power-management method called automatic power save delivery (APSD). The two APSD methods that are defined are scheduled automatic power save delivery (S-APSD) and unscheduled automatic power save delivery (U-APSD). The Wi-Fi Alliance's WMM Power Save (WMM-PS) certification is based on U-APSD."
            },

    ]
    };

    $(function () {
    $('#chapter7').slickQuiz({json: chapter7});
    $('#chapter8').slickQuiz({json: chapter8});
    $('#chapter9').slickQuiz({json: chapter9});
    });
    </script>
++++
