---
title: "Wireless Review"
date: "2014-03-29"
categories:
    - "hugo"
    - "fun"
    - "test"
---

= Wireless Review
:stem: latexmath
:experimental:
:diagram:
:source-highlighter: prettify

++++
<div id="slickQuiz">
<h1 class="quizName"><!-- where the quiz name goes --></h1>

<div class="quizArea">
<div class="quizHeader">

<a class="startQuiz" href="#">Get Started!</a>
</div>

<!-- where the quiz gets built -->
</div>

<div class="quizResults">
<h3 class="quizScore">You Scored: <span><!-- where the quiz score goes --></span></h3>

<h3 class="quizLevel"><strong>Ranking:</strong> <span><!-- where the quiz ranking level goes --></span></h3>

<div class="quizResultsCopy">
</div>
</div>
</div>

<script>
var quizJSON = {
    "info": {
        "name":    "",
        "main":    "Wireless Review Quiz",
    },
    "questions": [
        { // Question 1 - Multiple Choice, Single True Answer
            "q": "What number is the letter A in the English alphabet?",
            "a": [
                {"option": "8",      "correct": false},
                {"option": "14",     "correct": false},
                {"option": "1",      "correct": true},
                {"option": "23",     "correct": false} // no comma here
            ],
            "correct": "<p><span>That's right!</span> The letter A is the first letter in the alphabet!</p>",
            "incorrect": "<p><span>Uhh no.</span> It's the first letter of the alphabet. Did you actually <em>go</em> to kindergarden?</p>" // no comma here
        },
        { // Question 2 - Multiple Choice, Multiple True Answers, Select Any
            "q": "Which of the following best represents your preferred breakfast?",
            "a": [
                {"option": "Bacon and eggs",               "correct": false},
                {"option": "Fruit, oatmeal, and yogurt",   "correct": true},
                {"option": "Leftover pizza",               "correct": false},
                {"option": "Eggs, fruit, toast, and milk", "correct": true} // no comma here
            ],
            "select_any": true,
            "correct": "<p><span>Nice!</span> Your cholestoral level is probably doing alright.</p>",
            "incorrect": "<p><span>Hmmm.</span> You might want to reconsider your options.</p>" // no comma here
        }
    ]
    };
$(function () {
    $('#slickQuiz').slickQuiz();
});
</script>
++++

[latexmath]
++++
\sum_2^{x}{H}
++++
